version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static-backend/
      - media_value:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - backend

  backend:
    restart: always
    image: movrec/kinotochka_backend:v1
    env_file: devops.env
    command: gunicorn morec.wsgi:application --bind 0:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - postgres_db
      - redis

  postgres_db:
    image: "postgres:13.4-alpine"
    env_file: devops.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:6.2-alpine"
    restart: always
    volumes:
      - redis_data:/data

  celery:
    restart: always
    image: movrec/kinotochka_backend:v1
    env_file: devops.env
    command: celery -A morec worker -B -l INFO
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
  redis_data:
  static_value:
  media_value: