# Generated by Django 4.2.2 on 2023-08-03 18:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
            ],
            options={
                'verbose_name': 'Аватарка',
                'verbose_name_plural': 'Аватарки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Введите свой Email', max_length=255, unique=True, verbose_name='Почта')),
                ('username', models.CharField(blank=True, help_text='Введите свой логин', max_length=10, null=True, verbose_name='Логин')),
                ('first_name', models.CharField(blank=True, help_text='Введите своё имя', max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Введите свою фамилию', max_length=150, null=True, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введите свою дату рождения', null=True, verbose_name='Дата рождения')),
                ('sex', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], help_text='Выберите пол', null=True, verbose_name='Пол')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatars', to='users.avatar', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-pk'],
            },
        ),
    ]
