name: kinotochka_workflow

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: ./morec/
          push: true
          tags: movrec/kinotochka_backend:v1
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd morec_project/devops/
          sudo docker compose stop
          sudo docker compose rm -f backend
          sudo docker compose pull backend
          touch devops.env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> devops.env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> devops.env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> devops.env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> devops.env
          echo DEBUG=${{ secrets.DEBUG }} >> devops.env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> devops.env
          echo EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} >> devops.env
          echo EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} >> devops.env
          echo SITE_NAME=${{ secrets.SITE_NAME }} >> devops.env
          echo SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }} >> devops.env
          echo SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }} >> devops.env
          echo SOCIAL_AUTH_YANDEX_OAUTH2_KEY=${{ secrets.SOCIAL_AUTH_YANDEX_OAUTH2_KEY }} >> devops.env
          echo SOCIAL_AUTH_YANDEX_OAUTH2_SECRET=${{ secrets.SOCIAL_AUTH_YANDEX_OAUTH2_SECRET }} >> devops.env
          sudo docker compose up -d
